### ISSUE TITLE
cluster name hardcoded in some scripts, tmpl

### ISSUE THREAD

**Issue by xueshanf** [xuwang/aws-terraform#4]
Just change the CLUSTER_NAME variable from the default "coreos-cluster" at the top of Makefile is not enough. "coreos-cluster" is hard-coded in other places, which makes the cluster creation to fail.

**Comment by xuwang** [comment]
Fixed by merge request https://github.com/xuwang/aws-terraform/commit/79f2b272f395c8032b32430d67e61f5aba4e22e1

Thank you, Xueshan!
